#config_version=6

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: 'POTATO VALUE: (potato)'
        y: 40%

 

shots:
  my_first_shot:
    switch: s_right_inlane
#   center_rollover_shot:
#     switch: s_center_rollover
#     show_tokens:
#       led: l_left_rollover
#     profile: center_rollover_profile

# shot_profiles:
#   center_rollover_profile:
#     states:
#      - name: unlit
#        show: off
#      - name: flashing
#        show: flash 
#      - name: lit
#        show: on
#     loop: true

# Lane light change by flipper
  left_rollover:
    switch: s_left_rollover
    show_tokens:
      light: l_left_rollover
  center_rollover:
    switch: s_center_rollover
    show_tokens:
      light: l_center_rollover
  right_rollover:
    switch: s_right_rollover
    show_tokens:
      light: l_right_rollover

shot_groups:
  rollover_lanes:
    shots: left_rollover, center_rollover, right_rollover
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events:
      rollover_lanes_lit_complete: 1s

variable_player:
  s_right_inlane_active:
    score: 100
  s_left_flipper_active:
    score: 1000
    potato: 1
  s_right_flipper_active:
    potato: -2
  my_first_shot_hit:
    score: 42
  center_rollover_shot_hit:
    score: 125