#config_version=6

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger   

config:
 - config_ball_devices.yaml
 - config_coils.yaml
 - config_flippers.yaml
 - config_switches.yaml

modes:
 - base

displays:
  window:
    width: 800
    height: 600

lights:
 # Drop Targets
  l_T:
    number: 1
  l_I:
    number: 2
  l_M:
    number: 3
  l_E:
    number: 4
  l_Tb:
    number: 5
  l_R:
    number: 6
  l_A:
    number: 7
  l_V:
    number: 8
  l_Eb:
    number: 9
  l_L:
    number: 10
 
 # Rollover
  l_left_rollover:
    number: 11
  l_center_rollover:
    number: 12
  l_right_rollover:
    number: 13
  
  #Stand Ups
  l_left_standup:
    number: 14
  l_right_standup:
    number: 15
  l_top_lef_standup:
    number: 16
  l_top_left_standup_2:
    number: 17

  #Botom Lanes
  l_left_out_lane:
    number: 18
  l_right_out_lane:
    number: 19
  l_left_inlane:
    number: 20
  l_right_inlane: 
    number: 21

  # Center Targets
  l_left_center_target:
    number: 22
  l_center_center_target:
    number: 23
  l_right_center_target:
    number: 24

  # Scoops
  l_left_scoop:
    number: 25
  l_right_scoop:
    number: 26
  
  # Corridors
  l_left_corridor:
    number: 27
  l_left_corridor_2:
    number: 28
  l_right_corridor:
    number: 29
  
  # Botom 
  l_shot_again:
    number: 30
  l_bonusx100:
    number: 31
  l_bonusx1000:
    number: 32
  1_bonusx2000:
    number: 33
  l_bonusx5000: 
    number: 34
  l_bonusx7000:
    number: 35

keyboard:
  z:
    switch: s_left_flipper
  x:
    switch: s_right_flipper
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  p:
    switch: s_plunger
  s:
    switch: s_start
  q:
    switch: s_right_inlane

 

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

